name: win-x64_release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_win-x64_release:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'

      - name: Build
        run: |
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -S .\ -B .\build 
          cmake --build .\build --config Release --target MyLib
          cmake --build .\build --config Release --target MyTests

      - name: Test
        run: |
          cd .\RESULT\win-x64\Release
          .\test_MyLib.exe
